src = ["src"]
exclude = [
    "apps/**",
    "src/alembic/**",
    "docs/**",
    ".env",
    ".env.*",
]

[format]
docstring-code-format = true

[lint]
select = ["ALL"]
ignore = [
    "FA102",
    "INP001",
    "DTZ005",
    "DTZ007",
    "DTZ011",
    "FIX002",
    "FBT001",
    "FBT002",
]

[lint.per-file-ignores]
"scripts/**/*.py" = [
    "T201",
    "S603",
    "S604",
    "S607",
    "S104",
    "PLR2004",
    "E501",
    "ARG001",
]
